/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Estructura.Arista;
import Estructura.Grafo;
import Estructura.Evaluador;
import Estructura.MayorRiesgo;
import Estructura.Vertice;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.Random;
import javax.swing.JOptionPane;
import road2covid.pkg19.Lista;

/**
 * Ventana en la cual se visualizará el programa
 *
 * @author Camilo Cespedes, Luisa Escobar, Eduardo Rey
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Evaluador de caminos y probabilidades de contagio del grafo
     */
    private Evaluador ev;
    /**
     * Gráficos del panel de dibujo
     */
    private Graphics g;
    /**
     * Indicador de intención, si es verdadero se desea conocer caminos de
     * riesgo y posibles contagios, si es falso solo se desea saber la dirección
     * de las aristas de un nodo
     */
    private boolean verifRiesgo;

    /**
     * Crea una nueva Ventana
     */
    public Ventana() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setSize(940, 540);
        setTitle("Road 2 Covid-19");
        g = paneldeDibujo.getGraphics();
        ev = new Evaluador();
        verifRiesgo = false;
        sig.setVisible(false);
    }

    /**
     * Actualiza los dibujos en el panel de visualización luego de la
     * realización de una iteración de contagio
     */
    public void actualizarGrafo() {
        paneldeDibujo.setBackground(new java.awt.Color(203, 240, 221));
        for (Vertice vertice : ev.getGrafo().getVertices()) {
            if (vertice.isContagiado()) {
                g.setColor(Color.red);
                g.fillOval(vertice.getPosX() * 60, vertice.getPosY() * 60, 60, 60);
                g.setColor(Color.black);
                g.drawString("" + vertice.getvID(), vertice.getPosX() * 60 + 25, vertice.getPosY() * 60 + 25);
            } else {
                g.setColor(Color.GREEN);
                g.fillOval(vertice.getPosX() * 60, vertice.getPosY() * 60, 60, 60);
                g.setColor(Color.black);
                g.drawString("" + vertice.getvID(), vertice.getPosX() * 60 + 25, vertice.getPosY() * 60 + 25);
            }
            if (vertice.isMask()) {
                g.setColor(Color.white);
                drawMask((int) vertice.getPosX() * 60, (int) vertice.getPosY() * 60);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneldeDibujo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iniciarGrafo = new javax.swing.JButton();
        cantidad = new javax.swing.JTextField();
        numV = new javax.swing.JLabel();
        mask = new javax.swing.JComboBox<>();
        masc = new javax.swing.JLabel();
        verificarRiesgos = new javax.swing.JButton();
        iniciarContagio = new javax.swing.JButton();
        sig = new javax.swing.JButton();
        contIteraciones = new javax.swing.JLabel();
        contI = new javax.swing.JTextField();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(758, 477));
        setMinimumSize(new java.awt.Dimension(758, 477));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneldeDibujo.setBackground(new java.awt.Color(203, 240, 221));
        paneldeDibujo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneldeDibujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneldeDibujoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneldeDibujoLayout = new javax.swing.GroupLayout(paneldeDibujo);
        paneldeDibujo.setLayout(paneldeDibujoLayout);
        paneldeDibujoLayout.setHorizontalGroup(
            paneldeDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        paneldeDibujoLayout.setVerticalGroup(
            paneldeDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        getContentPane().add(paneldeDibujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        iniciarGrafo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botongraficar.png"))); // NOI18N
        iniciarGrafo.setBorderPainted(false);
        iniciarGrafo.setContentAreaFilled(false);
        iniciarGrafo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botongraficarmouse.png"))); // NOI18N
        iniciarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 160, 60));

        cantidad.setBackground(new java.awt.Color(203, 240, 221));
        cantidad.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 92, 36));

        numV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/personas.png"))); // NOI18N
        getContentPane().add(numV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        mask.setBackground(new java.awt.Color(203, 240, 221));
        mask.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        mask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos se protegen", "Nadie se protege", "Protección aleatoria" }));
        mask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maskActionPerformed(evt);
            }
        });
        getContentPane().add(mask, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        masc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/mascarilla.png"))); // NOI18N
        getContentPane().add(masc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 40));

        verificarRiesgos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/riesgossin.png"))); // NOI18N
        verificarRiesgos.setBorderPainted(false);
        verificarRiesgos.setContentAreaFilled(false);
        verificarRiesgos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/riesgoscon.png"))); // NOI18N
        verificarRiesgos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarRiesgosActionPerformed(evt);
            }
        });
        getContentPane().add(verificarRiesgos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 150, 60));

        iniciarContagio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botoniniciarcontagio.png"))); // NOI18N
        iniciarContagio.setBorderPainted(false);
        iniciarContagio.setContentAreaFilled(false);
        iniciarContagio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botoniniciarcontagiocon.png"))); // NOI18N
        iniciarContagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarContagioActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarContagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 150, 60));

        sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/siguientesin.png"))); // NOI18N
        sig.setBorderPainted(false);
        sig.setContentAreaFilled(false);
        sig.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/siguientecon.png"))); // NOI18N
        sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigActionPerformed(evt);
            }
        });
        getContentPane().add(sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 150, 60));

        contIteraciones.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        contIteraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/iteracion.png"))); // NOI18N
        getContentPane().add(contIteraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        contI.setEditable(false);
        contI.setBackground(new java.awt.Color(203, 240, 221));
        contI.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        contI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(contI, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 80, 30));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fondodef.png"))); // NOI18N
        bck.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Detecta la opción de iniciar un grafo y da la orden de crearlo
     *
     * @param evt Evento detectado
     */
    private void iniciarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarGrafoActionPerformed
        int typeMask = mask.getSelectedIndex() + 1;
        if (ev.getGrafo() == null) {
            ev.setGrafo(new Grafo(typeMask, Integer.parseInt(cantidad.getText())));
            graficar();
            System.out.println("");
        } else {
            int sw = JOptionPane.showOptionDialog(
                    null,
                    "¿Está seguro de borrar el grafo anterior?",
                    "Selector de opciones",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, // null para icono por defecto.
                    null, // null para YES, NO y CANCEL
                    null);
            if (sw == 0) {
                g.clearRect(0, 0, 710, 360);
                removeUbicaciones();
                ev.setGrafo(new Grafo(typeMask, Integer.parseInt(cantidad.getText())));
                ev.setIteraciones(0);
                contI.setText("" + ev.getIteraciones());
                iniciarContagio.setVisible(true);
                sig.setVisible(false);
                graficar();
            }

        }
        cantidad.setText("");
    }//GEN-LAST:event_iniciarGrafoActionPerformed
    /**
     * Detecta la clickear sobre un nodo y da la orden de realizar la acción
     * correspondiente
     *
     * @param evt Evento detectado
     */
    private void paneldeDibujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneldeDibujoMouseClicked

        for (Vertice vertice : ev.getGrafo().getVertices()) {

            int x = (int) (paneldeDibujo.getMousePosition().x / 60);
            int y = (int) (paneldeDibujo.getMousePosition().y / 60);

            if (x == vertice.getPosX()
                    && y == vertice.getPosY()) {
                graficar();
                x = x * 60;
                y = y * 60;
                if (vertice.isContagiado()) {
                    g.setColor(Color.red);
                    g.fillOval(x, y, 60, 60);
                    g.setColor(Color.black);
                    if (vertice.isMask()) {
                        g.setColor(Color.white);
                        drawMask(x, y);
                    }
                    g.drawString("" + vertice.getvID(), vertice.getPosX() * 60 + 25, vertice.getPosY() * 60 + 25);
                    StringBuffer sb = new StringBuffer("");
                    if (verifRiesgo) {
                        if (!ev.getGrafo().isAllInfected()) {
                            for (Arista arista : vertice.getAristas()) {
                                if (!arista.getvTerminal().isContagiado()) {
                                    sb.append(arista.getvTerminal().getvID() + ", ");
                                }
                            }
                            JOptionPane.showMessageDialog(null, "La persona " + vertice.getvID() + " puede contagiar a las personas: " + sb, "Información de riesgo", 0);
                        } else {
                            JOptionPane.showMessageDialog(null, "Esta persona no puede contagiar a nadie \n¡Ya todos están contagiados!");
                        }
                    }
                } else {
                    g.setColor(Color.GREEN);
                    g.fillOval(x, y, 60, 60);
                    if (vertice.isMask()) {
                        g.setColor(Color.white);
                        drawMask(x, y);
                    }
                    g.setColor(Color.black);
                    g.drawString("" + vertice.getvID(), vertice.getPosX() * 60 + 25, vertice.getPosY() * 60 + 25);
                    Lista<Vertice> camino = MayorRiesgo.FWarshall(ev.getGrafo().getMA(), ev.getGrafo(), vertice);
                    StringBuffer sb = new StringBuffer("");
                    if (camino != null && verifRiesgo) {
                        int contV = 0;
                        for (Vertice vertice1 : camino) {
                            contV++;
                            sb.append(vertice1.getvID());
                            if (contV <= camino.size() - 1) {
                                sb.append(" --> ");
                            }
                        }
                        JOptionPane.showMessageDialog(null, "El camino de mayor riesgo para el individuo " + vertice.getvID() + " es: " + sb, "Información de riesgo", 0);
                    }
                }
                if (vertice.isMask()) {
                    g.setColor(Color.white);
                    drawMask(x, y);
                }
                g.setColor(Color.YELLOW);

                for (Arista arista : vertice.getAristas()) {

                    Vertice v;
                    if (arista.getvInicial().equals(vertice)) {
                        v = arista.getvTerminal();
                    } else {
                        v = arista.getvInicial();
                    }

                    int x1 = v.getPosX() * 60;
                    int y1 = v.getPosY() * 60;

                    g.drawLine(x + 30, y + 30, x1 + 30, y1 + 30);
                }

                break;
            }

        }
    }//GEN-LAST:event_paneldeDibujoMouseClicked

    private void maskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maskActionPerformed
    /**
     * Detecta la opción de iniciar los contagios en un grafo y da la orden de
     * contagiar un vertice aleatorio
     *
     * @param evt Evento detectado
     */
    private void iniciarContagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarContagioActionPerformed
        if (ev.getGrafo() != null) {
            Random r = new Random();
            int vID_random = r.nextInt(ev.getGrafo().getVertices().size() - 1) + 1;
            ev.contagiar(vID_random);
            actualizarGrafo();
            iniciarContagio.setVisible(false);
            sig.setVisible(true);
            ev.setIteraciones(ev.getIteraciones() + 1);
            contI.setText("" + ev.getIteraciones());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor cree una comunidad antes que nada, \n sino, no hay a quién contagiar", "ERROR", 0);
        }
    }//GEN-LAST:event_iniciarContagioActionPerformed
    /**
     * Detecta la opción de pasar a la siguiente iteración de contagio y da la orden de contagiar a los nodos correspondientes
     *
     * @param evt Evento detectado
     */
    private void sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigActionPerformed
        if (ev.getGrafo().isAllInfected()) {
            JOptionPane.showMessageDialog(null, "Lastimosamente, ya todos fueron contagiados.");
        } else {
            ev.getGrafo().contagiar();
            actualizarGrafo();
            ev.setIteraciones(ev.getIteraciones() + 1);
            contI.setText("" + ev.getIteraciones());
        }
    }//GEN-LAST:event_sigActionPerformed

    /**
     * Detecta la opción de alternar entre detectar riesgos de contagio o solo visualizar cuando se clickee un Nodo, y alternar entre falso y verdadero la varriable que representa esta decisión
     * @param evt Evento detectado
     */
    private void verificarRiesgosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarRiesgosActionPerformed
        if (!verifRiesgo) {
            verifRiesgo = true;
        } else {
            verifRiesgo = false;
        }
    }//GEN-LAST:event_verificarRiesgosActionPerformed

    /**
     * Dibuja en el entorno gráfico del panel de visualización los vertices en sus posiciones y relacionados por las aristas correspondientes
     */
    public void graficar() {
        crearUbicaciones(ev.getGrafo().getVertices().size());
        g.setColor(new java.awt.Color(203, 240, 221));
        g.fillRect(2, 2, paneldeDibujo.getWidth() - 3, paneldeDibujo.getHeight() - 3);
        for (Vertice vertice : ev.getGrafo().getVertices()) {

            g.setColor(java.awt.Color.black);

            int x = vertice.getPosX() * 60;
            int y = vertice.getPosY() * 60;
            for (Arista arista : vertice.getAristas()) {

                int x1 = arista.getvTerminal().getPosX() * 60;
                int y1 = arista.getvTerminal().getPosY() * 60;
                g.drawLine(x + 30, y + 30, x1 + 30, y1 + 30);
            }

            g.setColor(java.awt.Color.black);
            g.fillOval(x, y, 60, 60);

            g.setColor(java.awt.Color.white);
            g.setFont(new Font("Tahoma", 0, 24));
            g.drawString("" + vertice.getvID(), vertice.getPosX() * 60 + 25, vertice.getPosY() * 60 + 25);

            if (vertice.isMask()) {
                drawMask(x, y);

            }
        }
    }

    /**
     * Inicializa las ubicaciones de cada vertice
     * @param n Numero de vertices
     */
    public void crearUbicaciones(int n) {

        int altura = paneldeDibujo.getHeight() / 60;
        int area = paneldeDibujo.getWidth() / 60;
        int x = 0, y = 0;
        for (int i = 0; i < n; i++) {
            do {
                x = (int) (Math.random() * area);
                y = (int) (Math.random() * altura);

            } while (comprobarUbicacion(x, y) && x != 0 && y != 0);
        }
    }

    /**
     * Vertifica que una ubicación en cuestión no esté ocupada por otro vértice
     * @param x Posocion en X a evaluar
     * @param y Posicion en Y a evaluar
     * @return booleano qe indica si la posición en cuestión está ocupada o no
     */
    public boolean comprobarUbicacion(int x, int y) {
        for (Vertice u : ev.getGrafo().getVertices()) {
            if (u.getPosX() == x && u.getPosY() == y) {
                return true;
            }
        }
        for (Vertice u : ev.getGrafo().getVertices()) {
            if (u.getPosX() == 0 && u.getPosY() == 0) {
                u.setPosX(x);
                u.setPosY(y);
                break;
            }
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bck;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField contI;
    private javax.swing.JLabel contIteraciones;
    private javax.swing.JButton iniciarContagio;
    private javax.swing.JButton iniciarGrafo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel masc;
    private javax.swing.JComboBox<String> mask;
    private javax.swing.JLabel numV;
    private javax.swing.JPanel paneldeDibujo;
    private javax.swing.JButton sig;
    private javax.swing.JButton verificarRiesgos;
    // End of variables declaration//GEN-END:variables

    private void removeUbicaciones() {
        for (Vertice vertice : ev.getGrafo().getVertices()) {
            vertice.setPosX(0);
            vertice.setPosY(0);
        }
    }

    private void drawMask(int x, int y) {
        g.drawLine(x, (int) (y + 30), (int) (x + 16), (int) (y + 37.5));
        g.drawLine(x + 30, (int) (y + 49), (int) (x + 7.5), (int) (y + 45));
        g.drawLine(x + 60, (int) (y + 30), (int) (x + 45), (int) (y + 37.5));
        g.drawLine(x + 30, (int) (y + 49), (int) (x + 55), (int) (y + 45));
        g.fillOval((int) (x + 15), y + 30, 30, 30);
    }
}
